"""Migracao Inicial

Revision ID: 5f1ce3c77a5a
Revises: 
Create Date: 2025-12-09 10:42:50.745318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1ce3c77a5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('aceito', sa.Boolean(), nullable=False),
    sa.Column('total_components', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=True),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('funcao', sa.String(length=50), nullable=False),
    sa.Column('telefone_pessoal', sa.String(length=20), nullable=False),
    sa.Column('rg_path', sa.String(length=255), nullable=False),
    sa.Column('cpf_path', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('cursando', sa.String(length=50), nullable=False),
    sa.Column('manequim', sa.String(length=10), nullable=False),
    sa.Column('tipo_sanguineo', sa.String(length=5), nullable=False),
    sa.Column('medicamento_controlado', sa.Boolean(), nullable=False),
    sa.Column('nome_medicamento_1', sa.String(length=100), nullable=True),
    sa.Column('declaracao_lida', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('equipes')
    # ### end Alembic commands ###
